#spring.config.activate.on-profile: local

spring:
  datasource:
    #url: jdbc:h2:file:./reservation;DB_CLOSE_DELAY=-1
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
